// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOQN__Xh4p9PjLvJcRXViTBAjPtCrhhtQ',
    appId: '1:1026956143217:web:633040984dbdd4618c89d0',
    messagingSenderId: '1026956143217',
    projectId: 'uni-hosptial-api',
    authDomain: 'uni-hosptial-api.firebaseapp.com',
    databaseURL: 'https://uni-hosptial-api-default-rtdb.firebaseio.com',
    storageBucket: 'uni-hosptial-api.firebasestorage.app',
    measurementId: 'G-JNHZVRYSVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEjRUSdr6jCm71KV5K7WTWpxOvUTO681k',
    appId: '1:1026956143217:android:71c2fc77e3ecf6958c89d0',
    messagingSenderId: '1026956143217',
    projectId: 'uni-hosptial-api',
    databaseURL: 'https://uni-hosptial-api-default-rtdb.firebaseio.com',
    storageBucket: 'uni-hosptial-api.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp5-xNauDw5rPqCrqUCtn_vdTR4_UE3gQ',
    appId: '1:1026956143217:ios:61901103211f00f08c89d0',
    messagingSenderId: '1026956143217',
    projectId: 'uni-hosptial-api',
    databaseURL: 'https://uni-hosptial-api-default-rtdb.firebaseio.com',
    storageBucket: 'uni-hosptial-api.firebasestorage.app',
    iosBundleId: 'com.robot3d.robotIntro3d',
  );
}
